/* UI */
export const SELECT_MENU_ITEM_UPDATE_BOOKING = 'SELECT_MENU_ITEM_UPDATE_BOOKING'
export const SELECT_MENU_ITEM_ALL_BOOKING = 'SELECT_MENU_ITEM_ALL_BOOKING'
export const SELECT_MENU_ITEM_ADD_BOOKING = 'SELECT_MENU_ITEM_ADD_BOOKING'
export const SELECT_MENU_ITEM_DEFAULT = SELECT_MENU_ITEM_ALL_BOOKING