/* UI */
const keys = {
    SELECT_MENU_ITEM_VOTANTES: 'SELECT_MENU_ITEM_VOTANTES',
    SELECT_MENU_ITEM_LIDERES: 'SELECT_MENU_ITEM_LIDERES',
    SELECT_MENU_ITEM_CONSULTAR: 'SELECT_MENU_ITEM_CONSULTAR',
    SELECT_MENU_ITEM_CERRAR_SESION: 'SELECT_MENU_ITEM_CERRAR_SESION',
    SELECT_MENU_ITEM_DEFAULT: 'SELECT_MENU_ITEM_ESCRITORIO'
}

export default keys